name: ADummyProject
options:
  postGenCommand: pod install
  deploymentTarget:
    iOS: 13.0

packages:
  Coordinator:
    url: git@github.com:goncalvesej/coordinator.git
    branch: main

attributes:
  ORGANIZATIONNAME: goncalvesej
    
configs:
  debug: debug
  test: debug
  release: release

settings:
  configs:
    test:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG TEST

targets:
  ADummyProject:
    platform: iOS
    type: application
    deploymentTarget: "13.0"
    sources:
      - ADummyProject
    dependencies:
      - package: Coordinator
    settings:
      base:
        INFOPLIST_FILE: ADummyProject/Info.plist
        ENABLE_BITCODE: NO
        PRODUCT_BUNDLE_IDENTIFIER: com.goncalvesej.$(PRODUCT_NAME).App
        SDKROOT: iphoneos
        SWIFT_VERSION: 5.7
        IPHONEOS_DEPLOYMENT_TARGET: 13.0
        TARGETED_DEVICE_FAMILY: "1"
        PRODUCT_NAME: ADummyProject

  ADummyProjectTests:
    platform: iOS
    type: bundle.unit-test
    deploymentTarget: "13.0"
    sources:
      - ADummyProjectTests
    dependencies:
      - target: ADummyProject
    settings:
      base:
        PRODUCT_NAME: ADummyProjectTests
    info:
      path: ADummyProjectTests/Info.plist
  
schemes:
  ADummyProject:
    build:
      targets:
        ADummyProject: all
        ADummyProjectTests: [test]
    test:
      config: test
      gatherCoverageData: true
      coverageTargets:
        - ADummyProject
      targets:
        - name: ADummyProjectTests
          parallelizable: true